### ISSUE TITLE
[Bug]: React Jest testing-library fails to import Chart.js

### ISSUE THREAD

**Issue by ironmanCCT** [reactchartjs/react-chartjs-2#1142]
### Would you like to work on a fix?

- [ ] Check this if you would like to implement a PR, we are more than happy to help you go through the process.

### Current and expected behavior

# Current Behavior
testing-library/react tests fail because of module import error.
# Expected Behavior
When simply testing a Create React App with a Chart, it's expected to render the App without errors. 

# setup
```
{
  "name": "cra",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "chart.js": "^4.1.1",
    "chartjs-adapter-date-fns": "^3.0.0",
    "chartjs-plugin-datalabels": "^2.2.0",
    "date-fns": "^2.29.3",
    "react": "^18.2.0",
    "react-chartjs-2": "^5.1.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "main": "index.js",
  "author": "",
  "license": "ISC"
}
```

`App.js`
```
import logo from "./logo.svg";
import "./App.css";
import Chart from "./Chart.js";
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
      </header>
      <Chart></Chart>
    </div>
  );
}

export default App;
```

`Chart.js`
```
import React, { useContext, useState, useEffect } from "react";
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  TimeScale,
  LineController,
  LineElement,
  PointElement,
  CategoryScale,
  LinearScale,
} from "chart.js/auto";
import { Chart } from "react-chartjs-2";
import "chartjs-adapter-date-fns";
import ChartDataLabels from "chartjs-plugin-datalabels";

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  TimeScale,
  LineController,
  LineElement,
  PointElement,
  CategoryScale,
  LinearScale,
  ChartDataLabels
);

export default function Canvas() {
  const augmentedData = [0, 1, 2];

  const chartData = {
    labels: ["a", "b", "c"],

    datasets: [
      {
        label: "Your Cost",
        hidden: true,
        fill: false,
        lineTension: 0,
        backgroundColor: "rgba(75,192,192,1)",
        borderColor: "rgba(0,0,0,1)",
        borderWidth: 2,
        data: augmentedData,
        datalabels: {
          color: "#000000",
          align: "bottom",
          offset: "5",
          display: "auto",

          backgroundColor: "rgba(255,255,255,0.5)",
        },
      },
    ],
  };
  console.log({ chartData });
  const options = {
    layout: {
      padding: { right: 5 },
    },
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: "bottom",
      },
    },
    scales: {
      x: {},
      y: {
        title: { display: true, text: "Dollar Amount" },
        stacked: false,
        grace: "2%",
        beginAtZero: true,
        ticks: {
          stepSize: 1,
        },
        suggestedMin: 0,
      },
    },
  };

  return (
    <>
      <div>
        <Chart type="line" data={chartData} height={300} options={options} />
      </div>
      {chartData ? (
        <div style={{ padding: "0.5rem", wordWrap: "wrap", whiteSpace: "pre" }}>
          {JSON.stringify(chartData, undefined, "\t")}
        </div>
      ) : null}
    </>
  );
}
```

### Reproduction

https://github.com/ironmanCCT/cra

### chart.js version

v4.1.1

### react-chartjs-2 version

v5.1.0

### Possible solution

All internet top level searches do not allow the tests to compile properly.

```
src/App.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/Documents/webdev/cra/node_modules/chart.js/auto/auto.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import {Chart, registerables} from '../dist/chart.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useContext, useState, useEffect } from "react";
    > 2 | import {
        | ^
      3 |   Chart as ChartJS,
      4 |   ArcElement,
      5 |   Tooltip,

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/Chart.js:2:1)
      at Object.<anonymous> (src/App.js:3:1)
      at Object.<anonymous> (src/App.test.js:2:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.936 s
Ran all test suites related to changed files.
```

**Comment by ironmanCCT** [comment]
[There is a lead here that this is caused by `jest`](https://github.com/facebook/jest/issues/12990) , but if we remove the `Chart.js` imports, all tests pass.

**Comment by ironmanCCT** [comment]
When trying to run tests with `NODE_OPTIONS=--experimental-vm-modules npm run test`
error:
```
src/App.test.jsx
  ● Test suite failed to run

    Must use import to load ES Module: /Users//Documents/webdev/cra/node_modules/chart.js/auto/auto.js

      1 | import React from "react";
    > 2 | import "chart.js/auto";
        | ^
      3 | import { Chart } from "react-chartjs-2";
      4 | export default function Canvas() {
      5 |   const augmentedData = [0, 1, 2];

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:972:21)
      at Object.<anonymous> (src/Chart.jsx:2:1)
      at Object.<anonymous> (src/App.jsx:3:1)
```

**Comment by asvitlica-vega** [comment]
Mocking the libraries could be the solution. Worked for us.

![mocks](https://user-images.githubusercontent.com/74365443/210765766-90cd402d-6bdc-4f09-a782-fd93887457c7.png)
![chart.js](https://user-images.githubusercontent.com/74365443/210765680-0e37c5ff-237a-433c-82c0-323eeb4a7b63.png)
![react-chartjs-2](https://user-images.githubusercontent.com/74365443/210765728-c49c070c-2064-4120-9271-7cae1950965c.png)

**Comment by dangreen** [comment]
@ironmanCCT Hi. Thank you for the issue reproduction. Please try [Chart.js v4.1.2](https://github.com/chartjs/Chart.js/releases/tag/v4.1.2)
