### ISSUE TITLE
TypeError: Cannot assign to read only property ... - Editing datasets with Redux

### ISSUE THREAD

**Issue by tervay** [reactchartjs/react-chartjs-2#524]
I'm a novice at React & Redux, so excuse me if there is an easy solution to this - I'm not able to find one currently.

[I'm utilizing `react-chartjs-2` with Redux](https://github.com/tervay/recalc) to create some charts with dynamic data based on `<input>`s. The core of the chart code can be reduced down to:

`slice.js`:

```
export const flywheelSlice = createSlice({
  name: "flywheel",
  initialState: {
    windupTime: Qty(0, "s"),
    windupTimeChart: {
      options: {},
      data: [],
    },
  },
  reducers: {
    // . . .
    generateWindupTimeChartReducer: (state, action) => {
      // . . .
      const data = [];
      const getTime = (ratio) => {
        // return some data
      };

      for (let i = start; i < end; i += step) {
        const time = getTime(i);
        if (time.scalar !== 0) {
          data.push({
            x: i,
            y: time.scalar,
          });
        }
      }

      state.windupTimeChart.data = _.orderBy(data, ["x"]);
      state.windupTimeChart.options = makeOptions( ... );
    },
  },
});
```

`Flywheel.js`:
```
  const chart = useRef(null);
  const windupTimeChart = useSelector((s) => s.flywheel.windupTimeChart);
  return (
        // . . .
        <Line
            data={{
              datasets: [
                {
                  data: windupTimeChart.data,
                },
              ],
            }}
            options={windupTimeChart.options}
            ref={chart}
          />
   );
```

I'm finding a very odd issue where updating data for one chart, updating data for another, and then updating data for the first one causes an error with read only data ... but not always.

The stacktrace can be found here:
```
TypeError: Cannot assign to read only property 'length' of object '[object Array]'
    at Array.splice (<anonymous>)
    at http://localhost:3000/static/js/1.chunk.js:91796:22
    at Array.map (<anonymous>)
    at ChartComponent.updateChart (http://localhost:3000/static/js/1.chunk.js:91790:60)
    at ChartComponent.componentDidUpdate (http://localhost:3000/static/js/1.chunk.js:91661:10)
    at commitLifeCycles (http://localhost:3000/static/js/1.chunk.js:112255:26)
    at commitLayoutEffects (http://localhost:3000/static/js/1.chunk.js:115207:11)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:92737:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:92786:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:92839:35)
    at commitRootImpl (http://localhost:3000/static/js/1.chunk.js:114949:13)
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:127010:16)
    at runWithPriority$1 (http://localhost:3000/static/js/1.chunk.js:103624:14)
    at commitRoot (http://localhost:3000/static/js/1.chunk.js:114791:7)
    at finishSyncRender (http://localhost:3000/static/js/1.chunk.js:114208:7)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/1.chunk.js:114194:11)
    at http://localhost:3000/static/js/1.chunk.js:103678:28
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:127010:16)
    at runWithPriority$1 (http://localhost:3000/static/js/1.chunk.js:103624:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/1.chunk.js:103673:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/1.chunk.js:103661:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/1.chunk.js:115283:7)
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:127010:16)
    at runWithPriority$1 (http://localhost:3000/static/js/1.chunk.js:103624:14)
    at flushPassiveEffects (http://localhost:3000/static/js/1.chunk.js:115224:16)
    at http://localhost:3000/static/js/1.chunk.js:115103:15
    at workLoop (http://localhost:3000/static/js/1.chunk.js:126954:38)
    at flushWork (http://localhost:3000/static/js/1.chunk.js:126910:20)
    at MessagePort.performWorkUntilDeadline (http://localhost:3000/static/js/1.chunk.js:126514:31)
```

which occurs here: https://github.com/jerairrest/react-chartjs-2/blob/master/src/index.js#L213

I assume this has to do with react-chartjs-2 editing the `data` property in place and Redux isn't a fan of that? Is there a workaround, or does anyone have any examples with Redux they could point me to?

**Comment by negebauer** [comment]
This also happens when rendering the `Line` component using a `data` prop contained in an object created using `useMemo`. Minimal reproduction example:

```js
import React, { useMemo } from 'react'
import { Line } from 'react-chartjs-2'

export default function LineChart({ data }) {
  const chartData = useMemo(() => ({ data: { datasets: [{ data }] } }), [data])

  return <Line data={chartData.data} />
}
```

When rerendering `LineChart` the following error is thrown:

```
index.js:207 Uncaught TypeError: Cannot assign to read only property 'length' of object '[object Array]'
    at Array.splice (<anonymous>)
    at index.js:207
    at Array.map (<anonymous>)
    at ChartComponent.updateChart (index.js:201)
    at ChartComponent.componentDidUpdate (index.js:62)
    at commitLifeCycles (react-dom.development.js:19835)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at commitRoot (react-dom.development.js:22381)
    at finishSyncRender (react-dom.development.js:21807)
    at performSyncWorkOnRoot (react-dom.development.js:21793)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)
```

```
index.js:1 The above error occurred in the <ChartComponent> component:
    in ChartComponent (created by Line)
    in Line (at LineChart.jsx:17)
    in LineChart (at Component.jsx:22)
```

**Comment by nasr18** [comment]
I'm also facing the same issue. I'm using Apollo-React. When I refresh the page, no problem. But when I navigate to that page or any state update causing this error. Any solution?

**Comment by tervay** [comment]
I wasn't able to find a solution without changing `react-chartjs-2` code itself. While this solution may not work for every use case, it works for mine, and I don't fully understand the code that I removed and it's effects on other people's code.

I replaced this:

```
    // We can safely replace the dataset array, as long as we retain the _meta property
    // on each dataset.
    this.chartInstance.config.data.datasets = nextDatasets.map(next => {
      const current =
        currentDatasetsIndexed[this.props.datasetKeyProvider(next)];

      if (current && current.type === next.type && next.data) {
        // Be robust to no data. Relevant for other update mechanisms as in chartjs-plugin-streaming.
        // The data array must be edited in place. As chart.js adds listeners to it.
        current.data.splice(next.data.length);
        next.data.forEach((point, pid) => {
          current.data[pid] = next.data[pid];
        });
        const { data, ...otherProps } = next;
        // Merge properties. Notice a weakness here. If a property is removed
        // from next, it will be retained by current and never disappears.
        // Workaround is to set value to null or undefined in next.
        return {
          ...current,
          ...otherProps
        };
      } else {
        return next;
      }
    });
```

with this:

```
    this.chartInstance.config.data.datasets = nextDatasets;
```

**Comment by nasr18** [comment]
@tervay instead of removing whole dataset, try fixing `current.data.splice(next.data.length)` line. Actual error happening here only.

**Comment by negebauer** [comment]
Given the comment about doing it in place I agree with @nasr18. Maybe change it so that instead of modifying it directly it first creates a copie and all modifications go to that copy

**Comment by asherccohen** [comment]
Hi. This is still an issue with charts that update with useMemo or redux useSelector. Any change it will get fixed soon?

**Comment by jhonnold** [comment]
@asherccohen Give [this library](https://www.npmjs.com/package/@reactchartjs/react-chart.js) a try. It is an updated version of this one and the code can be seen on the `react16` branch.

**Comment by raoufswe** [comment]
I'm facing the same issue with react apollo. I overcome the issue by cloning my data before passing it to the Line component.

I don't think it's the best workaround, and we should fix it from the library itself.

**Comment by asherccohen** [comment]
thanks @jhonnold that helped!

**Comment by jonra1993** [comment]
I had similar issue using redux and react-chartjs-2. I was able to solve it passing in this way 
`data: [...data] `instead of `data:data`

**Comment by chunaranimesh** [comment]
@nasr18  hey , i am having same problem while loading first time it is working fine then after navigating to the component or updating the state am getting this error, can u pls tell me the solution which worked for u.

**Comment by asherccohen** [comment]
You should make a shallow copy of your data. Spreading works.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
