### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'buildOrUpdateElements') after triggering getElementAtEvent a couple of times

### ISSUE THREAD

**Issue by acelaya** [reactchartjs/react-chartjs-2#732]
I have recently migrated from chartjs 2.x and react-chartjs-2 2.x to v3.x on both libraries.

Following migration guides I have managed to make mostly everything work just fine, but I'm experiencing a weird behavior and I still couldn't figure out what's the root cause (I have reproduced it in codesandbox with a simple example: https://codesandbox.io/s/compassionate-turing-jr33d?file=/src/App.tsx).

Basically I have a bar chart (used to be an HorizontalBar, now it's Bar with `{ indexAxis: 'y' }`), where I use `getElementAtEvent` to handle click events on every bar, in order to highlight it. This also affects other charts rendered in the same page.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2719332/132940873-11dbcb62-677f-4938-9b39-5ab3ea699ba5.gif)

The thing is that, after clicking a couple of times, I end up experiencing this crash:

```
Uncaught TypeError: Cannot read properties of null (reading 'buildOrUpdateElements')
    at Chart.update (chart.esm.js:7754)
    at updateChart (index.modern.js:137)
    at index.modern.js:157
    at invokePassiveEffectCreate (react-dom.development.js:23311)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3920)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3969)
    at invokeGuardedCallback (react-dom.development.js:4029)
    at flushPassiveEffectsImpl (react-dom.development.js:23393)
    at unstable_runWithPriority (scheduler.development.js:654)
    at runWithPriority$1 (react-dom.development.js:11326)
    at flushPassiveEffects (react-dom.development.js:23270)
    at performSyncWorkOnRoot (react-dom.development.js:22110)
    at react-dom.development.js:11380
    at unstable_runWithPriority (scheduler.development.js:654)
    at runWithPriority$1 (react-dom.development.js:11326)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11375)
    at flushSyncCallbackQueue (react-dom.development.js:11363)
    at discreteUpdates$1 (react-dom.development.js:22262)
    at discreteUpdates (react-dom.development.js:3730)
    at dispatchDiscreteEvent (react-dom.development.js:5912)

The above error occurred in the <ForwardRef> component:

    at http://localhost:3000/static/js/0.chunk.js:114788:18
    at http://localhost:3000/static/js/0.chunk.js:114928:20
    at div
    at div
    at DefaultChart (http://localhost:3000/static/js/main.chunk.js:21117:21)
    at div
    at CardBody (http://localhost:3000/static/js/0.chunk.js:172990:25)
    at div
    at Card (http://localhost:3000/static/js/0.chunk.js:172932:25)
    at GraphCard (http://localhost:3000/static/js/main.chunk.js:21339:20)
    at SortableBarGraph (http://localhost:3000/static/js/main.chunk.js:22523:21)
    at div
    at Route (http://localhost:3000/static/js/0.chunk.js:165082:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:165284:29)
    at div
    at Row (http://localhost:3000/static/js/0.chunk.js:179178:25)
    at section
    at VisitsStats (http://localhost:3000/static/js/main.chunk.js:19898:24)
    at http://localhost:3000/static/js/main.chunk.js:19003:24
    at http://localhost:3000/static/js/main.chunk.js:5703:33
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:162674:75)
    at Route (http://localhost:3000/static/js/0.chunk.js:165082:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:165284:29)
    at div
    at div
    at div
    at div
    at http://localhost:3000/static/js/main.chunk.js:3239:25
    at http://localhost:3000/static/js/main.chunk.js:7932:30
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:162674:75)
    at C (http://localhost:3000/static/js/0.chunk.js:165339:37)
    at Route (http://localhost:3000/static/js/0.chunk.js:165082:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:165284:29)
    at div
    at div
    at div
    at http://localhost:3000/static/js/main.chunk.js:1155:29
    at ConnectFunction (http://localhost:3000/static/js/0.chunk.js:162674:75)
    at http://localhost:3000/static/js/main.chunk.js:3630:25
    at C (http://localhost:3000/static/js/0.chunk.js:165339:37)
    at ErrorHandler (http://localhost:3000/static/js/main.chunk.js:2526:161)
    at Router (http://localhost:3000/static/js/0.chunk.js:164717:30)
    at BrowserRouter (http://localhost:3000/static/js/0.chunk.js:164337:35)
    at Provider (http://localhost:3000/static/js/0.chunk.js:162387:20)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorHandler.

Uncaught TypeError: Cannot read properties of undefined (reading 'disabled')
    at Chart._drawDataset (chart.esm.js:7973)
    at Chart._drawDatasets (chart.esm.js:7962)
    at Chart.draw (chart.esm.js:7917)
    at chart.esm.js:101
    at Map.forEach (<anonymous>)
    at Animator._update (chart.esm.js:74)
    at chart.esm.js:58
```

~I'm trying to set-up a simplified reproducible example. I'll attach it here once I have it.~ Se below

Also, I don't know 100% sure if this issue is caused by react-chartjs-2 or chartjs itself, or if the problem is that the logic I have is no longer compatible with the new signature of `getElementAtEvent`.

---

**EDIT**.

I have managed to reproduce it with a simple bar chart. This is a simplification of my code: https://codesandbox.io/s/compassionate-turing-jr33d?file=/src/App.tsx

Click on any of the bars a few times and you'll see the crash

**Comment by acelaya** [comment]
Ok, I have found out the reason for this. Probably more on Chart.js than this library.

In order to display "highlighted" data, I dynamically switch from 1 to 2 datasets (you can see the code in the codesandbox, or [here](https://github.com/shlinkio/shlink-web-client/issues/408#issuecomment-917615025) if it expires for some reason), depending if there's a "selected" bar or not. That's what's causing this error.

If instead I always have 2 datasets, but only one of them is filled with all `0`, the effect in practice is the same, but it does not crash.

**Comment by acelaya** [comment]
Actually, always having the dataset with all `0` can have some side effects, for example in tooltips, where it shows, or if the chart is a line chart and not a bar chart.

For those cases, my workaround is to dynamically render two different chart components, and that always has 2 datasets and one that always has 1.

```tsx
{highlightedData.length > 0 && (
  <Line
    data={generateChartData()}
    options={options}
    getElementAtEvent={chartElementAtEvent(labels, datasetsByPoint, setSelectedVisits) as any}
  />
)}
{highlightedData.length === 0 && (
  <Line
    data={generateChartData()}
    options={options}
    getElementAtEvent={chartElementAtEvent(labels, datasetsByPoint, setSelectedVisits) as any}
  />
)}
```
